routes/web.php
<?php


use App\Http\Controllers\HomeController;
use App\Http\Controllers\FacultiesController;
use App\Http\Controllers\KontrakTuriController;
use App\Http\Controllers\SpecialitiesController;
use App\Http\Controllers\StudentsController;
use App\Http\Controllers\StudentUsersController;
use App\Http\Controllers\TalimTiliController;
use App\Http\Controllers\TalimTuriController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\WorkController;
use App\Http\Controllers\YonalishTalimTuriController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

    Route::get('students/login', [StudentUsersController::class, 'login'])->name('student-user.login');
    Route::post('students/login', [StudentUsersController::class, 'handleLogin'])->name('student-user.handleLogin');

    Route::group(['prefix' => 'students', 'middleware' => ['auth:webstudent']], function ($router) {
        Route::get('', [StudentUsersController::class, 'index'])->name('student-user.home');
        Route::get('/logout', [StudentUsersController::class, 'index'])->name('student-user.logout');
    });
Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::get('/home', [HomeController::class, 'index'])->name('home');


    Route::get('users/profile/show/{user}', [UsersController::class, 'profileShow'])->name('users.profile.show');
    Route::post('users/profile/update', [UsersController::class, 'profileUpdate'])->name('users.profile.update');


    /////////////////////////////Prorektor///////////////////////////////////////////
    Route::group(['middleware' => 'admin'], function () {
        Route::prefix('admin')->group(function () {
            Route::resource('users', UsersController::class);
            Route::match(['GET', 'DELETE'], 'users/delete/{user}', [UsersController::class, 'delete'])->name('users.delete');

            /*******************************  Fakultetlar ************************************/
            Route::group(['prefix' => 'faculties'], function () {
                Route::get('/index', [FacultiesController::class, 'index'])->name('admin.faculties.index');
                Route::get('/create', [FacultiesController::class, 'create'])->name('admin.faculties.create');
                Route::post('/store', [FacultiesController::class, 'store'])->name('admin.faculties.store');
                Route::get('/edit/{id}', [FacultiesController::class, 'edit'])->name('admin.faculties.edit');
                Route::post('/update/{id}', [FacultiesController::class, 'update'])->name('admin.faculties.update');
                Route::get('/delete/{id}', [FacultiesController::class, 'delete'])->name('admin.faculties.delete');
                Route::post('/destroy/{id}', [FacultiesController::class, 'destroy'])->name('admin.faculties.destroy');
            });

            /*******************************  Talim shakllari ************************************/
            Route::group(['prefix' => 'talimturi'], function () {
                Route::get('/index', [TalimTuriController::class, 'index'])->name('admin.talimturi.index');
                Route::get('/create', [TalimTuriController::class, 'create'])->name('admin.talimturi.create');
                Route::post('/store', [TalimTuriController::class, 'store'])->name('admin.talimturi.store');
                Route::get('/edit/{id}', [TalimTuriController::class, 'edit'])->name('admin.talimturi.edit');
                Route::post('/update/{id}', [TalimTuriController::class, 'update'])->name('admin.talimturi.update');
                Route::get('/delete/{id}', [TalimTuriController::class, 'delete'])->name('admin.talimturi.delete');
                Route::post('/destroy/{id}', [TalimTuriController::class, 'destroy'])->name('admin.talimturi.destroy');
            });

            /*******************************  Shartnoma turlari ************************************/
            Route::group(['prefix' => 'kontraktturi'], function () {
                Route::get('/index', [KontrakTuriController::class, 'index'])->name('admin.kontraktturi.index');
                Route::get('/create', [KontrakTuriController::class, 'create'])->name('admin.kontraktturi.create');
                Route::post('/store', [KontrakTuriController::class, 'store'])->name('admin.kontraktturi.store');
                Route::get('/edit/{id}', [KontrakTuriController::class, 'edit'])->name('admin.kontraktturi.edit');
                Route::post('/update/{id}', [KontrakTuriController::class, 'update'])->name('admin.kontraktturi.update');
                Route::get('/delete/{id}', [KontrakTuriController::class, 'delete'])->name('admin.kontraktturi.delete');
                Route::post('/destroy/{id}', [KontrakTuriController::class, 'destroy'])->name('admin.kontraktturi.destroy');
            });

            /*******************************  Talim tillari ************************************/
            Route::group(['prefix' => 'talimtili'], function () {
                Route::get('/index', [TalimTiliController::class, 'index'])->name('admin.talimtili.index');
                Route::get('/create', [TalimTiliController::class, 'create'])->name('admin.talimtili.create');
                Route::post('/store', [TalimTiliController::class, 'store'])->name('admin.talimtili.store');
                Route::get('/edit/{id}', [TalimTiliController::class, 'edit'])->name('admin.talimtili.edit');
                Route::post('/update/{id}', [TalimTiliController::class, 'update'])->name('admin.talimtili.update');
                Route::get('/delete/{id}', [TalimTiliController::class, 'delete'])->name('admin.talimtili.delete');
                Route::post('/destroy/{id}', [TalimTiliController::class, 'destroy'])->name('admin.talimtili.destroy');
            });

            /*******************************  Yo'nalishlar ************************************/
            Route::group(['prefix' => 'specialities'], function () {
                Route::get('/index', [SpecialitiesController::class, 'index'])->name('admin.specialities.index');
                Route::get('/create', [SpecialitiesController::class, 'create'])->name('admin.specialities.create');
                Route::post('/store', [SpecialitiesController::class, 'store'])->name('admin.specialities.store');
                Route::get('/edit/{id}', [SpecialitiesController::class, 'edit'])->name('admin.specialities.edit');
                Route::post('/update/{id}', [SpecialitiesController::class, 'update'])->name('admin.specialities.update');
                Route::get('/delete/{id}', [SpecialitiesController::class, 'delete'])->name('admin.specialities.delete');
                Route::post('/destroy/{id}', [SpecialitiesController::class, 'destroy'])->name('admin.specialities.destroy');
            });

            /*******************************  Yo'nalish talim tui ************************************/
            Route::group(['prefix' => 'yonalishtalimturi'], function () {
                Route::get('/index', [YonalishTalimTuriController::class, 'index'])->name('admin.yonalishtalimturi.index');
                Route::get('/create', [YonalishTalimTuriController::class, 'create'])->name('admin.yonalishtalimturi.create');
                Route::post('/store', [YonalishTalimTuriController::class, 'store'])->name('admin.yonalishtalimturi.store');
                Route::get('/edit/{id}', [YonalishTalimTuriController::class, 'edit'])->name('admin.yonalishtalimturi.edit');
                Route::post('/update/{id}', [YonalishTalimTuriController::class, 'update'])->name('admin.yonalishtalimturi.update');
                Route::get('/delete/{id}', [YonalishTalimTuriController::class, 'delete'])->name('admin.yonalishtalimturi.delete');
                Route::post('/destroy/{id}', [YonalishTalimTuriController::class, 'destroy'])->name('admin.yonalishtalimturi.destroy');
            });

        });
    });
    /////////////////////////////Prorektor///////////////////////////////////////////
    Route::group(['middleware' => 'marketing'], function () {

    });


    /////////////////////////////Tasks///////////////////////////////////////////

    ////;/////////////////////////marketing_xodim///////////////////////////////////////////
    Route::group(['middleware' => 'marketing_xodim'], function () {
        Route::prefix('marketing_xodim')->group(function () {
            /***************************** Student  *****************************************************/
            Route::group(['prefix' => 'students'], function () {
                Route::get('/index', [StudentsController::class, 'index'])->name('students.index');
                Route::get('/create', [StudentsController::class, 'create'])->name('students.create');
                Route::post('/store', [StudentsController::class, 'store'])->name('students.store');
                Route::get('/edit/{model}', [StudentsController::class, 'edit'])->name('students.edit');
                Route::post('/update/{model}', [StudentsController::class, 'update'])->name('students.update');
                Route::post('/delete/{student}', [StudentsController::class, 'delete'])->name('students.delete');
                Route::match(['GET', 'DELETE'], '/delete/{student}', [StudentsController::class, 'delete'])->name('students.delete');
                Route::get('/specialty', [StudentsController::class, 'getSpecialty'])->name('students.specialty');

app/Models/User.php
<?php

namespace App\Models;

use App\Http\Filters\Filterable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Kyslik\ColumnSortable\Sortable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, Sortable, Filterable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public $timestamps = false;

    /**
     *  relation with roles
     */
    public function role()
    {
        return $this->hasOne(Role::class,'id','role_id');
    }


    public function getRoleName()
    {
        return $this->role->key;
    }
}

resources/views/users/columns.blade.php
<table class="table table-bordered">
	<thead>
	<tr>
		<th style="width: 50px;">@sortablelink('id', '#')</th>
		<th>Rasm</th>
		<th>@sortablelink('fio','FIO')</th>
		<th>@sortablelink('role.name','Rol')</th>
		<th>@sortablelink('username','Login')</th>
		<th>@sortablelink('phone','Telefon')</th>
		<th style="width:130px;">Harakatlar</th>
	</tr>
	<tr>
		@include('users.search')
	</tr>
	</thead>
	<tbody>
	@foreach($users as $user)
		<tr>
			<td>{{ $users->perPage()*($users->currentPage() - 1) + $loop->iteration }}</td>
			<td><img @if($user->image) src="{{asset('storage/users/'.$user->image)}}"  @else src="{{asset('img/noimg.jpg')}}" @endif style="max-width: 60px; min-width: 60px; max-height: 60px" alt=""></td>
			<td>{{$user->fio}}</td>
			<td>{{$user->role->name}}</td>
			<td>{{$user->username}}</td>
			<td>{{$user->phone}}</td>
			<td style="display: flex;">
				{{actionView(route('users.show',$user))}}
				{{actionEdit(route('users.edit',$user))}}
				@if( $user->role->key != 'admin')
					{{actionModalDelete($user->id)}}
				@endif
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
{{$users->links('pagination::bootstrap-4')}}

resources/views/users/create.blade.php
<form action="#" id="actionCreateForm">
    @csrf
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="username">Login*</label>
                <input type="username" class="form-control" name="username" id="username" placeholder="Login">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="password">Parol*</label>
                <input type="password" class="form-control" name="password" id="password" maxlength="20" minlength="6" pattern="[A-Za-z0-9]" placeholder="kamida 6 ta belgi">
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="fio">FIO*</label>
        <input type="text" class="form-control" id="fio" name="fio" placeholder="FIO">
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="role">Rol*</label>
                <select name="role" id="role" class="form-control">
                    <option value="">Tanlang..</option>
                    @foreach($roles as $role)
                        <option value="{{$role->id}}">{{$role->name}}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="col-md-6">
            <label for="phone">Telefon</label>
            <input type="text" class="form-control" id="phone" name="phone" placeholder="(998)90-999-99-99">
        </div>
    </div>
</form>
<div id="errorAlert">

</div>

resources/views/users/index.blade.php
@extends('layouts.app')
@section('content')
    <div id="content" class="content">
        <!-- begin breadcrumb -->
        <ol class="breadcrumb pull-left" style="margin-bottom: 10px;">
            <li class="breadcrumb-item"><a href="/">Asosiy</a></li>
            <li class="breadcrumb-item active">Foydalanuvchilar</li>
        </ol>
        <!-- begin row -->
        @include('users.modals')
        <div class="row">
            <div class="col-md-12 ui-sortable">
                <div class="panel panel-inverse" data-sortable-id="ui-buttons-1">
                    <div class="panel-heading">
                        <div class="panel-heading-btn">
                            <a onclick="showCreateModal()"  class="btn btn-xs btn-success">
                                Qo'shish <i class="fa fa-plus"></i>
                            </a>
                        </div>
                        <h4 class="panel-title">Foydalanuvchilar</h4>
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            @include('users.columns')
                        </div>
                </div>
            </div>
        </div>

        <!-- end row -->
    </div>
@endsection
@include('users.indexJs')

resources/views/users/indexJs.blade.php
@section('customJs')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.3.4/jquery.inputmask.bundle.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#phone').inputmask('+\\9\\9899-999-99-99');
        })


        function showAction(id) {
            var modal = $('#createModal');
            $.ajax({
                method: 'GET',
                url: 'users/' + id,
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                success: function (response) {
                    modal.find('.modal-header').html(response.header);
                    modal.find('.modal-body').html(response.content);
                    modal.find('.modal-footer').html(response.footer);
                    modal.modal('show');
                },
                error: function (response) {
                    $.gritter.add({
                        title: "Xatolik",
                        text: response.message,
                        class_name: "gritter-light",
                        image: '{{asset('assets/img/error.png')}}',
                        sticky: false,
                        time: 3000
                    });
                }
            });
        }

        function showCreateModal() {
            var modal1 = $('#createModal');
            console.log('alert')

            $.ajax({
                method: 'GET',
                url: '{{route('users.create')}}',
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                success: function (response) {
                    modal1.find('.modal-header').html(response.header);
                    modal1.find('.modal-body').html(response.content);
                    modal1.find('.modal-footer').html(response.footer);
                    modal1.modal('show');
                    $('#phone').inputmask('+\\9\\9899-999-99-99');

                },
                error: function (response) {
                    $.gritter.add({
                        title: "Xatolik",
                        text: response.message,
                        class_name: "gritter-light",
                        image: '{{asset('assets/img/error.png')}}',
                        sticky: false,
                        time: 3000
                    });
                }
            });
        }

        $(document).on('click', '#createSubmit', function (e) {
            e.preventDefault();
            var formData = $('#actionCreateForm').serialize();
            $.ajax({
                method: 'POST',
                url: '{{route('users.store')}}',
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                data: formData,
                success: function (response) {
                    $('#createModal').modal('hide');
                    $.gritter.add({
                        title: "Muvaffaqiyatli yakunladi",
                        text: response.success,
                        class_name: "gritter-light",
                        image: '{{asset('assets/img/success.png')}}',
                        sticky: false,
                        time: 200,
                        // after_close: function () {
                        //     window.location.reload();
                        // }
                    });
                    window.location.reload();

                },
                error: function (response) {
                    var errors = JSON.parse(response.responseText).errors;
                    var errorsHtml = '<ul>';
                    $.each(errors, function (index, value) {
                        errorsHtml += '<li><p class="text-danger">' + value + '</p></li>';
                    });
                    errorsHtml += '</ul>';
                    $('#errorAlert').html(errorsHtml);

                }
            });
        })

        function showDeleteModal(id) {
            var modal = $('#deleteModal');
            $('#createModal').modal('hide');
            $('#updateModal').modal('hide');
            $.ajax({
                method: 'GET',
                url:'/admin/users/delete/'+id,
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                success: function (response){
                    modal.find('.modal-header').html(response.header);
                    modal.find('.modal-body').html(response.content);
                    modal.find('.modal-footer').html(response.footer);
                    modal.modal('show');
                },
                error: function (response) {
                    $.gritter.add({
                        title: "Xatolik",
                        text: response.message,
                        class_name: "gritter-light",
                        image: '{{asset('assets/img/error.png')}}',
                        sticky: false,
                        time: 3000
                    });
                }
            });
        }

        function deleteUser(id){
            $.ajax({
                method: 'delete',
                url: 'users/delete/'+id,
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                success: function (response) {
                    $.gritter.add({
                        title: "Muvaffaqiyatli yakunladi",
                        text: response.success,
                        class_name: "gritter-light",
                        image: '{{asset('assets/img/success.png')}}',
                        sticky: false,
                        time: 200,
                    });
                    window.location.reload();

                },
                error: function (response){
                    $.gritter.add({
                        title: "Xatolik",
                        text: response.message,
                        class_name: "gritter-light",
                        image: '{{asset('assets/img/error.png')}}',
                        sticky: false,
                        time: 200
                    });

                }
            });

        }
    </script>
@endsection

resources/views/users/modals.blade.php
<div class="modal fade in" id="createModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">

            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">

            </div>
        </div>
    </div>
</div>

<div class="modal fade in" id="deleteModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">

            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">

            </div>
        </div>
    </div>
</div>

resources/views/users/search.blade.php
<form method="get" action="{{route('users.index')}}">
    @csrf
    <th></th>
    <th></th>
    <th><input type="text" name="fio" value="{{ request('fio') }}" class="form-control"></th>
    <th>
        <select class="form-control" name="role" id="">
            <option value="">Tanlang</option>
            @foreach($roles as $role)
                <option value="{{$role->id}}" @if(request('role') == $role->id)selected @endif>{{$role->name}}</option>
            @endforeach
        </select>
    </th>
    <th><input type="text" name="username" value="{{ request('username') }}" class="form-control"></th>
    <th><input type="text" name="phone" value="{{ request('phone') }}" class="form-control"></th>
    <th>
        <button type="submit" class="btn btn-warning btn-sm">
            <i class="fa fa-filter"></i> Qidiruv
        </button>
    </th>
</form>

resources/views/users/show.blade.php
@extends('layouts.app')
@section('content')
    <div id="content" class="content">
        <!-- begin breadcrumb -->
        <ol class="breadcrumb pull-left" style="margin-bottom: 10px;">
            <li class="breadcrumb-item"><a href="/">Asosiy</a></li>
            <li class="breadcrumb-item"><a href="{{route('users.index')}}">Foydalanuvchilar</a></li>
            <li class="breadcrumb-item active">Foydalanuvchi</li>
        </ol>
        <!-- begin row -->
        <div class="row">
            <div class="col-md-12 ui-sortable">
                <div class="panel panel-inverse" data-sortable-id="ui-buttons-1">
                    <div class="panel-heading">
                        <div class="panel-heading-btn">
                        </div>
                        <h4 class="panel-title">Foydalanuvchi</h4>
                    </div>
                    <div class="panel-body">
                        <div class="note note-success">
                            <div class="row">
                                <div class="col-md-8">
                                    <div class="table-responsive">
                                        <table class="table table-bordered">
                                            <tbody>
                                            <tr>
                                                <th width="250px">FIO</th>
                                                <td colspan="2">{{$user->fio??'_'}}</td>
                                                <th>Tug'ilgan kun</th>
                                                <td colspan="2">{{ $user->birthday ?? '_' }}</td>
                                            </tr>
                                            <tr>
                                                <th>Login</th>
                                                <td colspan="2">{{$user->username??'_'}}</td>
                                                <th>Telefon</th>
                                                <td colspan="2">{{$user->phone??'_'}}</td>
                                            </tr>
                                            <tr>
                                                <th>Jinsi</th>
                                                <td colspan="2">@if($user->sex == 1)Erkak @else @if($user->sex == 0)Ayol @else _ @endif @endif</td>
                                                <th>Status</th>
                                                <td colspan="2">@if($user->status == 1)Faol @else Faol emas @endif</td>
                                            </tr>
                                            <tr>
                                                <th>Fakultet</th>
                                                <td colspan="2">{{$user->faculty->name??'_'}}</td>
                                                <th>Rol</th>
                                                <td colspan="2">{{$user->role->name??'_'}}</td>
                                            </tr>
                                            <tr>
                                                <th>Yillik re'ja</th>
                                                <td colspan="2">
                                                    @if($user->annual_plan)
                                                        <a href="{{route('users.download',['documents', $user->annual_plan])}}" title="Yillik re'ja" class="btn btn-xs btn-primary">
                                                            <i class="fa fa-download"></i> {{$user->annual_plan}}
                                                        </a>
                                                    @else _
                                                    @endif
                                                </td>
                                                <th>Obyektivka (CV)</th>
                                                <td colspan="2">
                                                    @if($user->cv)
                                                        <a href="{{route('users.download',['documents', $user->cv])}}" title="Obyektivka" class="btn btn-xs btn-primary">
                                                            <i class="fa fa-download"></i> {{$user->cv}}
                                                        </a>
                                                    @else _
                                                    @endif
                                                </td>
                                            </tr>
                                            <tr>
                                                <th>Diplom</th>
                                                <td colspan="2">
                                                    @if($user->diplom)
                                                        <a href="{{route('users.download',['documents', $user->diplom])}}" title="Diplom" class="btn btn-xs btn-primary">
                                                            <i class="fa fa-download"></i> {{$user->diplom}}
                                                        </a>
                                                    @else _
                                                    @endif
                                                </td>
                                                <th>Passport</th>
                                                <td colspan="2">
                                                    @if($user->passport)
                                                        <a href="{{route('users.download',['documents', $user->passport])}}" title="Obyektivka" class="btn btn-xs btn-primary">
                                                            <i class="fa fa-download"></i> {{$user->passport}}
                                                        </a>
                                                    @else _
                                                    @endif
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <label class="control-label">Profil rasmi</label>
                                    <img id="preview" class="img-thumbnail"
                                         @if($user->image) src="{{asset('storage/users/'.$user->image)}}"  @else src="{{asset('img/noimg.jpg')}}" @endif
                                         alt=""
                                         style="object-fit: cover; width:100%; height: 300px;">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <a class="btn btn-inverse" href="{{route('users.index')}}" data-pjax="0"
                               style="margin: 2px;"><i class="fa fa-angle-double-left"></i> Ortga</a>
                            <a class="btn btn-info" href="{{route('users.edit',['user' => $user])}}" data-pjax="0"
                               style="margin: 2px;"><i class="fa fa-pencil"></i> Tahrirlash</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end row -->
        </div>
@endsection