routes/web.php
<?php


use App\Http\Controllers\HomeController;
use App\Http\Controllers\FacultiesController;
use App\Http\Controllers\KontrakTuriController;
use App\Http\Controllers\SpecialitiesController;
use App\Http\Controllers\StudentsController;
use App\Http\Controllers\StudentUsersController;
use App\Http\Controllers\TalimTiliController;
use App\Http\Controllers\TalimTuriController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\WorkController;
use App\Http\Controllers\YonalishTalimTuriController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

    Route::get('students/login', [StudentUsersController::class, 'login'])->name('student-user.login');
    Route::post('students/login', [StudentUsersController::class, 'handleLogin'])->name('student-user.handleLogin');

    Route::group(['prefix' => 'students', 'middleware' => ['auth:webstudent']], function ($router) {
        Route::get('', [StudentUsersController::class, 'index'])->name('student-user.home');
        Route::get('/logout', [StudentUsersController::class, 'index'])->name('student-user.logout');
    });
Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::get('/home', [HomeController::class, 'index'])->name('home');


    Route::get('users/profile/show/{user}', [UsersController::class, 'profileShow'])->name('users.profile.show');
    Route::post('users/profile/update', [UsersController::class, 'profileUpdate'])->name('users.profile.update');


    /////////////////////////////Prorektor///////////////////////////////////////////
    Route::group(['middleware' => 'admin'], function () {
        Route::prefix('admin')->group(function () {
            Route::resource('users', UsersController::class);
            Route::match(['GET', 'DELETE'], 'users/delete/{user}', [UsersController::class, 'delete'])->name('users.delete');

            /*******************************  Fakultetlar ************************************/
            Route::group(['prefix' => 'faculties'], function () {
                Route::get('/index', [FacultiesController::class, 'index'])->name('admin.faculties.index');
                Route::get('/create', [FacultiesController::class, 'create'])->name('admin.faculties.create');
                Route::post('/store', [FacultiesController::class, 'store'])->name('admin.faculties.store');
                Route::get('/edit/{id}', [FacultiesController::class, 'edit'])->name('admin.faculties.edit');
                Route::post('/update/{id}', [FacultiesController::class, 'update'])->name('admin.faculties.update');
                Route::get('/delete/{id}', [FacultiesController::class, 'delete'])->name('admin.faculties.delete');
                Route::post('/destroy/{id}', [FacultiesController::class, 'destroy'])->name('admin.faculties.destroy');
            });

            /*******************************  Talim shakllari ************************************/
            Route::group(['prefix' => 'talimturi'], function () {
                Route::get('/index', [TalimTuriController::class, 'index'])->name('admin.talimturi.index');
                Route::get('/create', [TalimTuriController::class, 'create'])->name('admin.talimturi.create');
                Route::post('/store', [TalimTuriController::class, 'store'])->name('admin.talimturi.store');
                Route::get('/edit/{id}', [TalimTuriController::class, 'edit'])->name('admin.talimturi.edit');
                Route::post('/update/{id}', [TalimTuriController::class, 'update'])->name('admin.talimturi.update');
                Route::get('/delete/{id}', [TalimTuriController::class, 'delete'])->name('admin.talimturi.delete');
                Route::post('/destroy/{id}', [TalimTuriController::class, 'destroy'])->name('admin.talimturi.destroy');
            });

            /*******************************  Shartnoma turlari ************************************/
            Route::group(['prefix' => 'kontraktturi'], function () {
                Route::get('/index', [KontrakTuriController::class, 'index'])->name('admin.kontraktturi.index');
                Route::get('/create', [KontrakTuriController::class, 'create'])->name('admin.kontraktturi.create');
                Route::post('/store', [KontrakTuriController::class, 'store'])->name('admin.kontraktturi.store');
                Route::get('/edit/{id}', [KontrakTuriController::class, 'edit'])->name('admin.kontraktturi.edit');
                Route::post('/update/{id}', [KontrakTuriController::class, 'update'])->name('admin.kontraktturi.update');
                Route::get('/delete/{id}', [KontrakTuriController::class, 'delete'])->name('admin.kontraktturi.delete');
                Route::post('/destroy/{id}', [KontrakTuriController::class, 'destroy'])->name('admin.kontraktturi.destroy');
            });

            /*******************************  Talim tillari ************************************/
            Route::group(['prefix' => 'talimtili'], function () {
                Route::get('/index', [TalimTiliController::class, 'index'])->name('admin.talimtili.index');
                Route::get('/create', [TalimTiliController::class, 'create'])->name('admin.talimtili.create');
                Route::post('/store', [TalimTiliController::class, 'store'])->name('admin.talimtili.store');
                Route::get('/edit/{id}', [TalimTiliController::class, 'edit'])->name('admin.talimtili.edit');
                Route::post('/update/{id}', [TalimTiliController::class, 'update'])->name('admin.talimtili.update');
                Route::get('/delete/{id}', [TalimTiliController::class, 'delete'])->name('admin.talimtili.delete');
                Route::post('/destroy/{id}', [TalimTiliController::class, 'destroy'])->name('admin.talimtili.destroy');
            });

            /*******************************  Yo'nalishlar ************************************/
            Route::group(['prefix' => 'specialities'], function () {
                Route::get('/index', [SpecialitiesController::class, 'index'])->name('admin.specialities.index');
                Route::get('/create', [SpecialitiesController::class, 'create'])->name('admin.specialities.create');
                Route::post('/store', [SpecialitiesController::class, 'store'])->name('admin.specialities.store');
                Route::get('/edit/{id}', [SpecialitiesController::class, 'edit'])->name('admin.specialities.edit');
                Route::post('/update/{id}', [SpecialitiesController::class, 'update'])->name('admin.specialities.update');
                Route::get('/delete/{id}', [SpecialitiesController::class, 'delete'])->name('admin.specialities.delete');
                Route::post('/destroy/{id}', [SpecialitiesController::class, 'destroy'])->name('admin.specialities.destroy');
            });

            /*******************************  Yo'nalish talim tui ************************************/
            Route::group(['prefix' => 'yonalishtalimturi'], function () {
                Route::get('/index', [YonalishTalimTuriController::class, 'index'])->name('admin.yonalishtalimturi.index');
                Route::get('/create', [YonalishTalimTuriController::class, 'create'])->name('admin.yonalishtalimturi.create');
                Route::post('/store', [YonalishTalimTuriController::class, 'store'])->name('admin.yonalishtalimturi.store');
                Route::get('/edit/{id}', [YonalishTalimTuriController::class, 'edit'])->name('admin.yonalishtalimturi.edit');
                Route::post('/update/{id}', [YonalishTalimTuriController::class, 'update'])->name('admin.yonalishtalimturi.update');
                Route::get('/delete/{id}', [YonalishTalimTuriController::class, 'delete'])->name('admin.yonalishtalimturi.delete');
                Route::post('/destroy/{id}', [YonalishTalimTuriController::class, 'destroy'])->name('admin.yonalishtalimturi.destroy');
            });

        });
    });
    /////////////////////////////Prorektor///////////////////////////////////////////
    Route::group(['middleware' => 'marketing'], function () {

    });


    /////////////////////////////Tasks///////////////////////////////////////////

    ////;/////////////////////////marketing_xodim///////////////////////////////////////////
    Route::group(['middleware' => 'marketing_xodim'], function () {
        Route::prefix('marketing_xodim')->group(function () {
            /***************************** Student  *****************************************************/
            Route::group(['prefix' => 'students'], function () {
                Route::get('/index', [StudentsController::class, 'index'])->name('students.index');
                Route::get('/create', [StudentsController::class, 'create'])->name('students.create');
                Route::post('/store', [StudentsController::class, 'store'])->name('students.store');
                Route::get('/edit/{model}', [StudentsController::class, 'edit'])->name('students.edit');
                Route::post('/update/{model}', [StudentsController::class, 'update'])->name('students.update');
                Route::post('/delete/{student}', [StudentsController::class, 'delete'])->name('students.delete');
                Route::match(['GET', 'DELETE'], '/delete/{student}', [StudentsController::class, 'delete'])->name('students.delete');
                Route::get('/specialty', [StudentsController::class, 'getSpecialty'])->name('students.specialty');

app/Models/Faculty.php
<?php

namespace App\Models;

use App\Http\Filters\Filterable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;

class Faculty extends Model
{
    use HasFactory, Sortable, Filterable;
    public $timestamps = false;
    protected $table = 'faculties';

    protected $fillable = [
        'id',
        'name',
        'key',
    ];

}

app/Http/Controllers/FacultiesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Filters\FacultyFilter;
use App\Models\Faculty;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;
use Symfony\Component\HttpFoundation\Response;

class FacultiesController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index(FacultyFilter $filter)
    {
        $datas = Faculty::filter($filter)
            ->sortable()
            ->paginate(15);
        return  view('faculties.index',compact('datas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function create()
    {
        $header = '<h5 class="modal-title" id="createActionLabel">Qo\'shish</h5>';
        $footer = '<button type="button" class="btn btn-sm btn-white"
                                data-dismiss="modal">Yopish</button>
                        <a href="#" id="createSubmit" class="btn btn-sm btn-success">Saqlash</a>';
        $view = view('faculties.create');
        return ['header' => $header, 'content' => $view->render(), 'footer' => $footer];
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),[
            'name' => 'required'
        ],[
            'name.required' => 'Nomi maydoni to\'ldirilishi shart'
        ]);
        if ($validator->fails()) {
            return response()->json([
                'error' => true,
                'message' => $validator->errors(),
            ], Response::HTTP_UNPROCESSABLE_ENTITY);
        }

            $faculty = new Faculty();
            $faculty->name = $request->name;
            $faculty->key = Str::slug($request->name);
            $faculty->save();
            return ['message' => 'Fakultet yaratildi'];
    }

    public function edit($id)
    {
        $faculty = Faculty::where('id', $id)->first();
        $header = '<h5 class="modal-title" id="createActionLabel">Qo\'shish</h5>';
        $footer = '<button type="button" class="btn btn-sm btn-white"
                                data-dismiss="modal">Yopish</button>
                        <a href="#" onclick="updateFaculty('.$id.')" class="btn btn-sm btn-success">Saqlash</a>';
        $view = view('faculties.edit',compact('faculty'));
        return ['header' => $header, 'content' => $view->render(), 'footer' => $footer];
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Faculty  $faculty
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(Request $request, $id)
    {
        if($data = $this->validate($request,[
            'name' => 'required'
        ],[
            'name.required' => 'Nomi maydoni kiritilishi shart!'
        ])){
            $faculty = Faculty::where('id',$id)->first();
            $faculty->name = $data['name'];
            $faculty->key = Str::slug($data['name']);
            $faculty->save();
            return ['message' => 'Fakultet tahrirlandi'];
        }
    }


    /*
       * education type delete
       */
    public function delete($id)
    {
        $faculty = Faculty::where('id', $id)->first();
        $header = '<h5 class="modal-title" id="createActionLabel">Tasdiqlang</h5>';
        $footer = '<button type="button" class="btn btn-sm btn-white pull-left"
                                data-dismiss="modal">Yopish</button>
                        <a href="#" onclick="deleteFaculty('.$faculty->id.')"class="btn btn-sm btn-danger" style="margin: 2px;">
            Ha</a>';
        $content = '<h4>Rostdan ham o\'chirishni xohlaysizmi?</h4>';
        return ['header' => $header, 'content' => $content, 'footer' => $footer];
    }

    public function destroy($id)
    {
        $model = Faculty::where('id', $id)->first();
        if ($model) {
            $model->delete();
        }
        return back()->withSuccess(__("message.data_deleted"));
    }
}

resources/views/faculties/_columns.blade.php
<table class="table table-bordered kv-grid-table table-striped table-condensed">
    <thead>
    <tr>
        <th width="20">@sortablelink('id','#')</th>
        <th width="20">ID</th>
        <th>@sortablelink('name','Nomi')</th>
        <th>@sortablelink('key','Kalit')</th>
        <th>Harakatlar</th>
    </tr>
    <tr>
        @include('faculties.search')
    </tr>
    </thead>
    <tbody>
    @foreach($datas  as $data)
        <tr>
            <td>{{ $datas->perPage()*($datas->currentPage() - 1) + $loop->iteration }}</td>
            <td>{{ $data->id }}</td>
            <td>{{$data->name}}</td>
            <td>{{$data->key}}</td>
            <td class="skip-export kv-align-center kv-align-middle crud-datatable"
                style="width:50px;" data-col-seq="11">
                {{actionModalEdit($data->id)}}
                {{actionModalDelete($data->id)}}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
{{$datas->links('pagination::bootstrap-4')}}

resources/views/faculties/create.blade.php
<form action="#" id="actionCreateForm" class="form-horizontal">
    @csrf
    <div class="row">
        <div class="col-md-12">
            <div>
                <label for="name"> Nomi</label>
                <input type="text" id="name"  name="name" class="form-control">
                <div class="help-block"></div>
            </div>
        </div>
    </div>
    <div id="errorAlert" style="display: none;">

    </div>
</form>

resources/views/faculties/delete.blade.php
<div class="modal fade" id="delete_modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Amalni tasdiqlang</h4>
            </div>
            <div class="modal-body">
                <h4>Rostdan ham o'chirishni xohlaysizmi?</h4>
            </div>
            <form method="POST" id="delete_form" >
                @csrf
                <input id="id_delete" name="id" type="hidden">
                <div class="modal-footer">
                    <a href="javascript:;" class="btn btn-sm btn-white pull-left" data-dismiss="modal">Yo'q</a>
                    <button type="submit" class="btn btn-sm btn-danger">Ha</button>
                </div>
            </form>

        </div>
    </div>
</div>

resources/views/faculties/edit.blade.php
<form action="#" id="actionUpdateForm" class="form-horizontal">
    @csrf
    <div class="row">
        <div class="col-md-12">
            <div>
                <label for="name"> Nomi</label>
                <input type="text" id="name"  name="name" value="{{$faculty->name ?? ''}}" class="form-control">
                <div class="help-block"></div>
            </div>
        </div>
    </div>
    <div id="errorAlert" style="display: none;">

    </div>
</form>

resources/views/faculties/index.blade.php
@extends('layouts.app')
@section('content')
    @include('faculties.delete')
    <!-- begin page-header -->
    <div id="content" class="content">
        <!-- begin breadcrumb -->
        <ol class="breadcrumb pull-left" style="margin-bottom: 10px;">
            <li class="breadcrumb-item"><a href="/">Asosiy</a></li>
            <li class="breadcrumb-item active">Fakultetlar</li>
        </ol>
        @include('faculties.modals')
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-inverse">
                    <div class="panel-heading">
                        <div class="panel-heading-btn">
                            <a onclick="showCreateModal()"  title="Qo'shish"
                               class="btn btn-xs btn-success">
                                <i class="fa fa-plus"></i> Qo'shish
                            </a>
                        </div>
                        <h4 class="panel-title">Fakultetlar</h4>
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive kv-grid-container">
                            @include('faculties._columns')
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@include('faculties.indexJs')

resources/views/faculties/indexJs.blade.php
@section('customJs')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.3.4/jquery.inputmask.bundle.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#phone').inputmask('+\\9\\9899-999-99-99');
        })


        function showCreateModal() {
            var modal1 = $('#createModal');
            $.ajax({
                method: 'GET',
                url: '{{route('admin.faculties.create')}}',
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                success: function (response) {
                    modal1.find('.modal-header').html(response.header);
                    modal1.find('.modal-body').html(response.content);
                    modal1.find('.modal-footer').html(response.footer);
                    modal1.modal('show');

                },
                error: function (response) {
                    $.gritter.add({
                        title: "Xatolik",
                        text: response.message,
                        class_name: "gritter-light",
                        image: '{{asset('assets/img/error.png')}}',
                        sticky: false,
                        time: 3000
                    });
                }
            });
        }

        $(document).on('click', '#createSubmit', function (e) {
            e.preventDefault();
            var formData = $('#actionCreateForm').serialize();
            $.ajax({
                method: 'POST',
                url: '{{route('admin.faculties.store')}}',
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                data: formData,
                success: function (response) {
                    if(response.status == 422){
                        var errors = JSON.parse(response.responseText).errors;
                        var errorsHtml = '<ul>';
                        $.each(errors, function (index, value) {
                            errorsHtml += '<li><p class="text-danger">' + value + '</p></li>';
                        });
                        errorsHtml += '</ul>';
                        $('#errorAlert').html(errorsHtml);
                    }
                    $('#createModal').modal('hide');
                    $.gritter.add({
                        title: "Muvaffaqiyatli yakunladi",
                        text: response.success,
                        class_name: "gritter-light",
                        image: '{{asset('assets/img/success.png')}}',
                        sticky: false,
                        time: 200,
                        // after_close: function () {
                        //     window.location.reload();
                        // }
                    });
                    window.location.reload();

                },
                error: function (response) {
                    var errors = JSON.parse(response.responseText).message;
                    var errorsHtml = '<ul>';
                    $.each(errors, function (index, value) {
                        errorsHtml += '<li><p class="text-danger">' + value + '</p></li>';
                    });
                    errorsHtml += '</ul>';
                    // $('#errorAlert').html(errorsHtml);
                    var errorAlert =  $('#errorAlert');
                    errorAlert.css('display','block');
                    errorAlert.html(errorsHtml)
                }
            });
        })

        function showUpdateModal(id) {
            var modal1 = $('#updateModal');
            $.ajax({
                method: 'GET',
                url: '/admin/faculties/edit/'+id,
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                success: function (response) {
                    modal1.find('.modal-header').html(response.header);
                    modal1.find('.modal-body').html(response.content);
                    modal1.find('.modal-footer').html(response.footer);
                    modal1.modal('show');

                },
                error: function (response) {
                    $.gritter.add({
                        title: "Xatolik",
                        text: response.message,
                        class_name: "gritter-light",
                        image: '{{asset('assets/img/error.png')}}',
                        sticky: false,
                        time: 3000
                    });
                }
            });
        }

        function updateFaculty(id)
        {
            var form = $('#actionUpdateForm')[0];
            inputs = new FormData(form);
            $.ajax({
                method: 'POST',
                url: '/admin/faculties/update/'+id,
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                data: inputs,
                processData: false,
                contentType: false,
                cache: false,
                success: function (response) {
                    $('#createModal').modal('hide');
                    $.gritter.add({
                        title: "Muvaffaqiyatli yakunladi",
                        text: response.success,
                        class_name: "gritter-light",
                        image: '{{asset('assets/img/success.png')}}',
                        sticky: false,
                        time: 200,
                        // after_close: function () {
                        //     window.location.reload();
                        // }
                    });
                    window.location.reload();

                },
                error: function (response){
                    var errors = JSON.parse(response.responseText).errors;
                    var errorsHtml = '<ul>';
                    $.each(errors, function (index, value) {
                        errorsHtml += '<li><p class="text-danger">' + value + '</p></li>';
                    });
                    errorsHtml +='</ul>';
                    var errorAlert =  $('#errorAlert');
                    errorAlert.css('display','block');
                    errorAlert.html(errorsHtml)
                }
            });
        }


        function showDeleteModal(id) {
            var modal = $('#deleteModal');
            $('#createModal').modal('hide');
            $('#updateModal').modal('hide');
            $.ajax({
                method: 'GET',
                url:'/admin/faculties/delete/'+id,
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                success: function (response){
                    modal.find('.modal-header').html(response.header);
                    modal.find('.modal-body').html(response.content);
                    modal.find('.modal-footer').html(response.footer);
                    modal.modal('show');
                },
                error: function (response) {
                    $.gritter.add({
                        title: "Xatolik",
                        text: response.message,
                        class_name: "gritter-light",
                        image: '{{asset('assets/img/error.png')}}',
                        sticky: false,
                        time: 3000
                    });
                }
            });
        }

        function deleteFaculty(id){
            $.ajax({
                method: 'post',
                url: '/admin/faculties/destroy/'+id,
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                success: function (response) {
                    $.gritter.add({
                        title: "Muvaffaqiyatli yakunladi",
                        text: response.success,
                        class_name: "gritter-light",
                        image: '{{asset('assets/img/success.png')}}',
                        sticky: false,
                        time: 200,
                    });
                    window.location.reload();

                },
                error: function (response){
                    $.gritter.add({
                        title: "Xatolik",
                        text: response.message,
                        class_name: "gritter-light",
                        image: '{{asset('assets/img/error.png')}}',
                        sticky: false,
                        time: 200
                    });

                }
            });

        }
    </script>
@endsection

resources/views/faculties/update.blade.php
{{--@extends('layouts.app')--}}
{{--@section('content')--}}
{{--    <div id="content" class="content">--}}
{{--        <!-- begin breadcrumb -->--}}
{{--        <ol class="breadcrumb pull-left" style="margin-bottom: 10px;">--}}
{{--            <li class="breadcrumb-item"><a href="/">Asosiy</a></li>--}}
{{--            <li class="breadcrumb-item"><a href="{{route('admin.faculties.index')}}">Fakultetlar</a></li>--}}
{{--            <li class="breadcrumb-item active">Tahrirlash</li>--}}
{{--        </ol>--}}
{{--        <!-- begin row -->--}}
{{--        <div class="row">--}}
{{--            <div class="col-md-12 ui-sortable">--}}
{{--                <div class="panel panel-inverse" data-sortable-id="ui-buttons-1">--}}
{{--                    <div class="panel-heading">--}}
{{--                        <div class="panel-heading-btn">--}}
{{--                        </div>--}}
{{--                        <h4 class="panel-title">Tahrirlash</h4>--}}
{{--                    </div>--}}
{{--                    <div class="panel-body">--}}
{{--                        <form action="{{route('admin.users.update', ['user' => $user->id])}}" method="post"--}}
{{--                              autocomplete="off">--}}
{{--                            @csrf--}}
{{--                            @method('PUT')--}}
{{--                            <div>--}}
{{--                                @if ($errors->any())--}}
{{--                                    <div class="alert alert-danger">--}}
{{--                                        <ul>--}}
{{--                                            @foreach ($errors->all() as $error)--}}
{{--                                                <li>{{ $error }}</li>--}}
{{--                                            @endforeach--}}
{{--                                        </ul>--}}
{{--                                    </div>--}}
{{--                                @endif--}}
{{--                                <div class="row">--}}
{{--                                    <div class="col-md-12" style="text-align: center;">--}}
{{--                                        <div class="">--}}
{{--                                            <label class="btn btn-info" style="min-width:80%;" for="image"><span class="fa fa-camera"></span> Profil rasmi</label>--}}
{{--                                            <input type="text" id="name" class="image_input" name="name">--}}
{{--                                            <div class="help-block"></div>--}}
{{--                                        </div>--}}
{{--                                    </div>--}}
{{--                                </div>--}}

{{--                            </div>--}}
{{--                            <br>--}}
{{--                            <div class="row">--}}
{{--                                <div class="col-md-12">--}}
{{--                                    <div class="form-group pull-right">--}}
{{--                                        <a class="btn btn-inverse" href="{{route('admin.faculties.index')}}"><span--}}
{{--                                                    class="fa fa-angle-double-left"></span> Ortga</a>--}}
{{--                                        <button type="submit" class="btn btn-success">Saqlash</button>--}}
{{--                                    </div>--}}
{{--                                </div>--}}
{{--                            </div>--}}
{{--                        </form>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--            <!-- end row -->--}}
{{--        </div>--}}
{{--        @endsection--}}
{{--        @section('customJs')--}}
{{--            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.3.4/jquery.inputmask.bundle.min.js"></script>--}}
{{--            <script src="{{asset('assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js')}}"></script>--}}
{{--            <script>--}}
{{--                $(document).ready(function () {--}}
{{--                    $('#name').on('input', function () {--}}
{{--                        $(this).next().css('display', 'none');--}}
{{--                    });--}}
{{--                });--}}
{{--            </script>--}}
{{--@endsection--}}